Hand Written Functions (Practice)

In [ ]:
import numpy as np
import torch
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
import kagglehub
path = kagglehub.dataset_download("yasserh/breast-cancer-dataset")
print("Path to dataset files:", path)

Using Colab cache for faster access to the 'breast-cancer-dataset' dataset.
Path to dataset files: /kaggle/input/breast-cancer-dataset

In [ ]:
import os
files = os.listdir(path)
full_path = os.path.join(path, files[0])
df=pd.read_csv(full_path)

In [ ]:
df.shape

(569, 32)

In [ ]:
print(df.columns)

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [ ]:
df.sample(5)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
449,911157302,M,21.100,20.52,138.10,1384.0,0.09684,0.11750,0.15720,0.115500,...,25.68,32.07,168.20,2022.0,0.1368,0.3101,0.43990,0.22800,0.2268,0.07425
486,913102,B,14.640,16.85,94.21,666.0,0.08641,0.06698,0.05192,0.027910,...,16.46,25.44,106.00,831.0,0.1142,0.2070,0.24370,0.07828,0.2455,0.06596
511,915664,B,14.810,14.70,94.66,680.7,0.08472,0.05016,0.03416,0.025410,...,15.61,17.58,101.70,760.2,0.1139,0.1011,0.11010,0.07955,0.2334,0.06142
346,898678,B,12.060,18.90,76.66,445.3,0.08386,0.05794,0.00751,0.008488,...,13.64,27.06,86.54,562.6,0.1289,0.1352,0.04506,0.05093,0.2880,0.08083
318,894329,B,9.042,18.90,60.07,244.5,0.09968,0.19720,0.19750,0.049080,...,10.06,23.40,68.62,297.1,0.1221,0.3748,0.46090,0.11450,0.3135,0.10550

In [ ]:
df.drop(columns=['id'], inplace=True)

In [ ]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [ ]:
x_train, x_test, y_train, y_test=train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

In [ ]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
x_train

array([[-0.14926812, -1.90189122, -0.14413868, ..., -0.56592909,
        -0.26361397, -0.63235676],
       [-0.62629854, -0.11327053, -0.55193381, ...,  0.64798599,
         3.10029288,  3.23843358],
       [ 1.44271507,  1.29273284,  1.67377766, ...,  0.98112299,
         0.50068666,  1.09019879],
       ...,
       [-0.85211176, -0.98222671, -0.84858637, ..., -0.66436279,
         0.54333005, -0.57794237],
       [ 0.63261015, -0.8047476 ,  0.54192146, ...,  0.36308601,
        -0.93606731, -0.61025091],
       [-0.73355982, -0.2377364 , -0.72927156, ..., -0.852035  ,
        -1.08695928, -0.37898975]])

In [ ]:
y_train

76     B
31     M
12     M
302    M
398    B
      ..
437    B
80     B
381    B
508    B
304    B
Name: diagnosis, Length: 455, dtype: object

In [ ]:
encoder = LabelEncoder()
y_train= encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0])

In [ ]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
x_train_tensor.shape

torch.Size([455, 30])

In [ ]:
class MySimpleNN():
  def __init__(self,X):
    self.weights = torch.rand(X.shape[1],1,dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)
  def forward(self,X):
    z=torch.matmul(X,self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred
  def loss_function(self,y_pred, y):
    epsilon = 1e-7
    loss = -(y * torch.log(y_pred + epsilon) +
             (1 - y) * torch.log(1 - y_pred + epsilon)).mean()
    return loss

In [ ]:
lr=0.1
epochs=25

In [ ]:
model=MySimpleNN(x_train_tensor)
for epoch in range(epochs):
  y_pred=model.forward(x_train_tensor)
  # print(y_pred)
  loss=model.loss_function(y_pred,y_train_tensor)
  # print(loss.item())
  loss.backward()
  with torch.no_grad():
    model.weights -= lr*model.weights.grad
    model.bias -= lr*model.bias.grad
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  print(f'Epoch:{epoch+1}, Loss:{loss.item()}')

Epoch:1, Loss:3.6211672105430472
Epoch:2, Loss:3.507593566124667
Epoch:3, Loss:3.3888614537300903
Epoch:4, Loss:3.2652010728427614
Epoch:5, Loss:3.1367184990330275
Epoch:6, Loss:3.0032207266179682
Epoch:7, Loss:2.864043847957906
Epoch:8, Loss:2.7184543358730116
Epoch:9, Loss:2.5667451131218715
Epoch:10, Loss:2.4104441711143485
Epoch:11, Loss:2.251329614298845
Epoch:12, Loss:2.0909781254737423
Epoch:13, Loss:1.9313895228688396
Epoch:14, Loss:1.774196230501805
Epoch:15, Loss:1.6212284490774616
Epoch:16, Loss:1.475978895477504
Epoch:17, Loss:1.3422722207849507
Epoch:18, Loss:1.2229723139412934
Epoch:19, Loss:1.1201025555827517
Epoch:20, Loss:1.0349233339668227
Epoch:21, Loss:0.9673131047416518
Epoch:22, Loss:0.9152941823115888
Epoch:23, Loss:0.8756829913919232
Epoch:24, Loss:0.8453402120511548
Epoch:25, Loss:0.8217585671935417

In [ ]:
model.weights

tensor([[ 0.0769],
        [ 0.2120],
        [-0.2045],
        [-0.2546],
        [-0.2177],
        [-0.2054],
        [ 0.0637],
        [ 0.3383],
        [-0.1831],
        [ 0.5419],
        [ 0.2059],
        [ 0.6407],
        [-0.0061],
        [-0.2904],
        [ 0.1408],
        [ 0.3264],
        [ 0.4707],
        [-0.5028],
        [-0.0885],
        [-0.3110],
        [ 0.4252],
        [ 0.1855],
        [ 0.0154],
        [-0.4234],
        [ 0.2150],
        [-0.1655],
        [ 0.3394],
        [ 0.2048],
        [ 0.1890],
        [-0.4195]], dtype=torch.float64, requires_grad=True)

In [ ]:
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred>0.6).float()
  accuracy = (y_pred==y_test_tensor).float().mean()
  print(f'Accuracy:{accuracy}')

Accuracy:0.5200061798095703